site_name: STUF
site_author: Patrick Cahan
copyright: Copyright &copy; 2025 Patrick Cahan
repo_url: https://github.com/CahanLab/STUF

use_directory_urls: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

theme:
  name: material
  font:
    text: Noto Sans
  palette:
    primary: blue grey
  logo: img/logoGlow.png
  favicon: img/logo.png
  features:
    - content.footnote.tooltips
    - navigation.expand
    - toc.integrate
#    - navigation.tabs
#    - navigation.tabs.sticky
#    - navigation.sections

markdown_extensions:
  - md_in_html
  - footnotes
  - admonition
  - attr_list
  - tables
  - def_list
  - toc:
      title: On this page
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            separate_signature: true
            docstring_section_style: list
            heading_level: 3
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: True

nav:
  - Installation: install.md
  - Tutorials: 
    - 'Quickstart': notebooks/quickstart.ipynb
    - 'Plotting': notebooks/plotting.ipynb
    - 'Tools': notebooks/tools.ipynb
  - Example data: example_data.md
  - API:
    - 'Utilities': 'utils.md'
    - 'Tools': 'tools.md'
    - 'Plots': 'plotting.md'


